### ISSUE TITLE
Package not found

### ISSUE THREAD

**Issue by StephanDisberg** [Cannonb4ll/laravel-philips-hue#1]
Hi, thanks for this package. However, the 'composer require dennissmink/laravel-philips-hue' command (as stated in the docs) is not working. Composer returns a not found notice. Running 'composer require cannonb4ll/laravel-philips-hue' does the trick. 

It would be too bad to miss this package ;) 

Thanks!

**Comment by Cannonb4ll** [comment]
Whoops!

Got confused indeed, should be `composer require cannonb4ll/laravel-philips-hue`.

Changed in readme, thank you!
