### ISSUE TITLE
Undefined function array_first

### ISSUE THREAD

**Issue by justkidding96** [Cannonb4ll/laravel-philips-hue#3]
Hi,

 I've got an error inside HueUser.php on line 33. Is array_first a valid function? I searched already the Laravel and PHP docs but couldn't find any helper or something.

**Comment by Cannonb4ll** [comment]
Hi!

Which Laravel version are you using?

**Comment by justkidding96** [comment]
Hi @Cannonb4ll atm Laravel 6.

**Comment by Cannonb4ll** [comment]
Ah, I see where the issue is then. Will issue a fix in a moment.

**Comment by justkidding96** [comment]
@Cannonb4ll Also can I help you with this lib. I already started to implement the sensor resource. But do you want to split  the motion, temperature and ambient light sensor?

**Comment by Cannonb4ll** [comment]
1.3 just released, fix for the helper non-existent in newer Laravel version.

About your other question, would appreciate some help :) Would be nice if you can split those up yes.
