### ISSUE TITLE
Missing Guzzle requirement in composer

### ISSUE THREAD

**Issue by allentje** [Cannonb4ll/laravel-philips-hue#4]
The Guzzle package is missing from the composer file which will throw an error if the lib is used without installing guzzle.
The solution would be to add the requirement to the composer.json.

I can open a PR with these changes if you would like?
I would also be open to help developing the lib further if you would like some help?

**Comment by Cannonb4ll** [comment]
Oh yes PRs are certainly welcome and will be creditted!

Additional help will be very welcome as well 🙏

**Comment by allentje** [comment]
Great, would you be open for strict typing and type hinting the methods or would you prefer to keep it restricted to phpdoc only?
I think i will try to add some unit tests to the lib.

**Comment by Cannonb4ll** [comment]
My preference is phpdocblock, which is now missing. I have not done much since I released this but I intend too update some stuff.

**Comment by allentje** [comment]
I am so sorry I completely forgot about this.
I see you have added it to the composer json now.
