### ISSUE TITLE
Add .env.example

### ISSUE THREAD

**Issue by szepeviktor** [Cannonb4ll/laravel-philips-hue#9]
with all required and optional variables
and some instructions

**Comment by szepeviktor** [comment]
# 😿

**Comment by Cannonb4ll** [comment]
Sorry, I missed the why and how, can you elaborate?

**Comment by szepeviktor** [comment]
If you don't have an env.example file all you have to rely on is the .env file - or maybe looking throughout the README.

You must have seen env.example files in many other projects.

**Comment by Cannonb4ll** [comment]
But the .env variables are already in the README:

```
PHILIPS_HUE_CLIENT_ID=
PHILIPS_HUE_CLIENT_SECRET=
PHILIPS_HUE_APP_ID=
PHILIPS_HUE_DEVICE_ID=
PHILIPS_HUE_USERNAME= <-- We will get this in below step
```

It is useless to add an .env.example file with just those variables.

**Comment by szepeviktor** [comment]
> It is useless to add an .env.example file with just those variables.

Yes.
Adding some instructions where/how to get those values would be the point.
